# Generated by Django 5.0.3 on 2024-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='balance',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='balance',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='balance',
            name='transaction_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_dollar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_euro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
