# Generated by Django 5.0.3 on 2024-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_balance_amount_balance_charge_balance_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='method',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_dollar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_euro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_inr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
